### ISSUE TITLE
Use of fcntl module prevents running on Windows

### ISSUE THREAD

**Issue by ctoth** [araile/see#6]
fcntl is Only being used to determine the terminal width.

It looks like there are a couple of ways of getting the terminal width on Windows, see:
https://code.activestate.com/recipes/440694-determine-size-of-console-window-on-windows/

**Comment by efotinis** [comment]
I've made a [patch](http://pastebin.com/eJHwR89N), but it uses `win32console` from pywin32. That's pretty much a standard package for Python on Windows, but feel free to go with `ctypes` if you'd like.

**Comment by ctoth** [comment]
We should very much use the ctypes method as it is guaranteed to work in 
any Windows Python, and not just those with pywin32 already installed.

On 4/17/2015 9:41 AM, Elias Fotinis wrote:
>
> I've made a patch <http://pastebin.com/eJHwR89N>, but it uses 
> |win32console| from pywin32. That's pretty much a standard package for 
> Python on Windows, but feel free to go with |ctypes| if you'd like.
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/inky/see/issues/6#issuecomment-94012007>.
>


-- 
		-Q

	Accessible Software for the Blind
http://GetAccessibleApps.com

**Comment by inky** [comment]
Thanks for spotting this.

I'm unable to test in Windows, but for now I've pushed a preliminary patch to skip the terminal width feature in Windows (it's not essential to see.py). Ultimately though I would like to use the ctypes approach, for the same reason given by ctoth.

**Comment by efotinis** [comment]
OK, here's [another](https://gist.github.com/efotinis/636d2be871b0cd202efa) one using `ctypes`. Looks messy, though.

**Comment by araile** [comment]
Should be working in Windows now in v1.3.0. Thanks again!
